# https://docs.github.com/pt/actions/automating-builds-and-tests/building-and-testing-ruby
name: Linting

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure git repository
        uses: actions/checkout@v3

      - name: Configure Ruby 2.7
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7'

      - name: Install Development dependencies
        run: |
          bundle config set --local gemfile Gemfile.local
          bundle install

      - name: Run Linting - Rubocop
        run: rubocop
