name: Cucumber

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.7'

      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
        with:
          chromedriver-version: '102.0.5005.61'

      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: cucumber -p ci_debug -p qa
